### ISSUE TITLE
Difference_to_previous_day incorrect?

### ISSUE THREAD

**Issue by TheSpirit** [ThisIsBenny/rki-vaccination-data#21]
Difference to the previous day seems incorrect. Can you please check this?
Thanks

**Comment by ThisIsBenny** [comment]
thanks for the hint. The RKI has added to new columns why the index of the column for 2nd_vaccination.difference_to_the_previous_day isn't anymore correct:
<img width="815" alt="Bildschirmfoto 2021-02-04 um 20 37 06" src="https://user-images.githubusercontent.com/66417262/106946110-fa434f00-6728-11eb-971b-722a9c09bffc.png">

Issue will be fixed with #22

**Comment by niredp** [comment]
are you going to add these new columns to your API?
Thank you for the nice work!

**Comment by ThisIsBenny** [comment]
@niredp i can do this late :-) yesterday, it was to late why i have only fix the bug :-)

**Comment by ThisIsBenny** [comment]
@niredp i have added in the newest version (#23) the new fields.
