### ISSUE TITLE
Janssen in section "at lest one vaccination" and "fully vaccinated"

### ISSUE THREAD

**Issue by therealrandallflagg** [ThisIsBenny/rki-vaccination-data#39]
Hi @ThisIsBenny,

I don't know if this is really an issue. Janssen vaccination appears in the section "at least one vaccination" AND in the section "fully vaccinated", so the total of vaccinations given is too high (exactly about the number of Janssen vaccinations).

**Comment by ThisIsBenny** [comment]
Thanks for the info. i will fix it

**Comment by therealrandallflagg** [comment]
Hi @ThisIsBenny,

I think the totals are still wrong because they are wrong in the Excel sheet. For the section "at least one vaccination" the total per state is the total ("vaccinated") minus Janssen or am I wrong here ;-) ? Greetings @therealrandallflagg

**Comment by ThisIsBenny** [comment]
It isn't easy for Janssen 😅 there was also another thread where we discussed this topic.

The RKI changed the excel sheet a lot of time, why the structure of the API Response is a little bit...

I calculate the quote based on the first vaccination and not "also second" => fully vaccinated. You can count Janssen to fully vaccinated, but the quote is calculated based on first vaccination. So the calculated quote will be lower if i remove the janssen numbers.

I think i haven't the perfect solution for this.
To be honest, I would need to build a V2 API so everything is clean in there. At the moment everything is a little bit mixed up due to the unexpected changes on the excel sheet.
